project:
  type: book

book:
  title: "Thống kê sinh học: Từ lý thuyết đến ứng dụng"
  author: ThS. Nguyễn Tấn Đức | Chuyên đào tạo kỹ năng R
  site-url: https://www.tuhocr.com/
  date: last-modified
  date-format: "[Cập nhật:] YYYY MMMM DD"
  # cover-image: cover.png
  favicon: favicon.png
  # comments:
  #   hypothesis:
  #     theme: clean
  chapters:
    - index.qmd
    - part: cac-lenh-do-thi-can-ban-su-dung-base-r-graphics.qmd  
      chapters:
        - huong-dan-ve-do-thi-cot-base-r-graphics.qmd
        - huong-dan-cach-thay-doi-do-rong-cot-trong-barplot.qmd
        - tinh-huong-base-r-graphics-thuong-gap.qmd
        - huong-dan-ve-do-thi-nhieu-truc-y.qmd
        - huong-dan-ve-do-thi-bang-package-lattice.qmd
        - so-sanh-cu-phap-ve-do-thi-qua-cac-package-khac-nhau.qmd
        # - cac-lenh-do-thi-su-dung-package-ggplot2.qmd
    - part: co-so-ly-thuyet.qmd
      chapters:
        - tong-quan-tai-lieu.qmd
        - khoang-tin-cay.qmd
        # - phan-tich-anova-2-yeu-to-kieu-rcbd-trong-r.qmd
        - huong-dan-phan-tich-t-test-trong-r.qmd
        - phan-tich-anova-2-yeu-to-trong-r.qmd
        - so-sanh-ket-qua-giua-parametric-va-non-parametric-anova.qmd
        - phan-tich-ancova-trong-r.qmd
        - cac-lenh-r-thuong-dung-khi-thuc-hien-thong-ke-mo-ta.qmd
        - quy-trinh-phan-tich-logistic-regression.qmd
        - khai-niem-bootstrap-qua-vi-du-tinh-trung-binh-mau.qmd
        - bo-tri-thi-nghiem-toi-uu-hoa-bang-r.qmd
        - workflow-phan-tich-thong-ke-qua-dataset-iris.qmd
        # - huong-dan-phan-tich-logistic-regression.qmd
        - example-partial-least-squares-and-principal-component-regression.qmd
        - quy-cach-ghi-ky-hieu-toan-hoc-trong-cong-thuc-xac-suat-thong-ke.qmd
        - tai-lieu-phan-tich-pca.qmd
        - xay-dung-mo-hinh-GAM-trong-r.qmd
    - part: "Kỹ thuật xử lý dữ liệu"
      chapters:
        - huong-dan-convert-tu-csv-qua-tsv-trong-r.qmd
        - huong-dan-cach-lam-tron-so-trong-r.qmd
        - huong-dan-show-all-data-tren-console.qmd   
        - ky-thuat-reshape-du-lieu.qmd
        - ky-thuat-kiem-tra-missing-value.qmd
    - references.qmd
    
  sidebar:
    style: "docked"
    search: true
    title: "<a href='https://thongkesinhhoc.com/'>Thống kê sinh học: Từ lý thuyết đến ứng dụng</a>"
          
bibliography: F:/VAULT12/GRAND/grand.bib
number-sections: true
format:
  html:
    toc: false
    theme: default
    page-layout: full
  # pdf:
  #   documentclass: scrreprt
engine: knitr
knitr:
  opts_chunk:
    R.options:
      width: 200


