# <b>Tài liệu phân tích PCA</b> 

Phân tích Principal Component Analysis (PCA) là kỹ thuật giảm chiều của dataset rút gọn còn 2 trục PC1 và PC2 (hay 3 trục PC1, PC2, PC3) nhằm giúp phân tách ra sự khác biệt giữa các nhóm (variables) hoặc giữa các cá thể/observation với nhau.

`https://www.sthda.com/english/articles/31-principal-component-methods-in-r-practical-guide/118-principal-component-analysis-in-r-prcomp-vs-princomp/`

There are two general methods to perform PCA in R :

* Spectral decomposition which examines the covariances / correlations between variables

* Singular value decomposition which examines the covariances / correlations between individuals

Để tìm hiểu nhanh về kỹ thuật vẽ đồ thị PCA ta cần điểm qua các tài liệu sau:

1. Concept chung về PCA theo cách ngắn gọn dễ hiểu. StatQuest: Principal Component Analysis (PCA), Step-by-Step. `https://www.youtube.com/watch?v=FgakZw6K1QQ`

2. GS. Nguyễn Văn Tuấn. Bài giảng 83: Principal Component Analysis. `https://www.youtube.com/watch?v=uEEp5WYNHVY`

3. Alboukadel Kassambara - Practical Guide to Principal Component Methods in R. `https://studyr.netlify.app/ref/kassambara_principal_component_methods.pdf`

4. Biện luận đồ thị PCA. `https://applyr.netlify.app/b1/Principal_component_analysis.pdf`

5. Cơ sở toán học của phân tích PCA. `https://applyr.netlify.app/b1/I.T.%20Jolliffe%20-%20Principal%20Component%20Analysis-Springer%20(2002).pdf`

Khi phân tích PCA sẽ có giai đoạn gom cụm dữ liệu. Bạn cần trang bị kiến thức về các thuật toán clustering ở đây.

6. Advances in K-means Clustering. `https://applyr.netlify.app/b1/Advances%20in%20K-means%20Clustering.pdf`

7. Alboukadel Kassambara -Practical Guide To Cluster Analysis in R.  `https://applyr.netlify.app/b1/Practical%20Guide%20to%20Cluster%20Analysis%20in%20R.%20Unsupervised%20Machine%20Learning.pdf`

8. Model-Based Clustering, Classification, and Density Estimation Using mclust in R. `https://applyr.netlify.app/b1/Model-Based%20Clustering.pdf`


